<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

namespace Rpc;

/**
 * Protobuf type <code>rpc.users</code>
 */
interface usersInterface
{
    /**
     * Method <code>create</code>
     *
     * @param \Rpc\CreateRequest $request
     * @return \Rpc\CreateResponse
     */
    public function create(\Rpc\CreateRequest $request);

    /**
     * Method <code>read</code>
     *
     * @param \Rpc\ReadRequest $request
     * @return \Rpc\ReadResponse
     */
    public function read(\Rpc\ReadRequest $request);

    /**
     * Method <code>update</code>
     *
     * @param \Rpc\UpdateRequest $request
     * @return \Rpc\UpdateResponse
     */
    public function update(\Rpc\UpdateRequest $request);

    /**
     * Method <code>del</code>
     *
     * @param \Rpc\DelRequest $request
     * @return \Rpc\DelResponse
     */
    public function del(\Rpc\DelRequest $request);

}

